// <auto-generated />
using System;
using Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebApp.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RegisterDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("WillAttend")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BirthDate = new DateTime(2001, 3, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "lale@gmail.com",
                            Name = "Lale",
                            Phone = "1234567890",
                            RegisterDate = new DateTime(2025, 2, 24, 13, 15, 47, 185, DateTimeKind.Local).AddTicks(3544),
                            Surname = "Bozkurt",
                            WillAttend = 1
                        },
                        new
                        {
                            Id = 2,
                            BirthDate = new DateTime(2002, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "nihal@gmail.com",
                            Name = "Nihal",
                            Phone = "0987654321",
                            RegisterDate = new DateTime(2025, 2, 24, 13, 15, 47, 186, DateTimeKind.Local).AddTicks(6348),
                            Surname = "Sengul",
                            WillAttend = 0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
